In [1]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [4]:
tf.constant('Hello, TensorFlow!')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow!'>

In [5]:
t=tf.constant([[12.0, 14.0,8.0],[22.0, 24.0, 18.0]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[12., 14.,  8.],
       [22., 24., 18.]], dtype=float32)>

In [11]:
t[1,1:]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([24., 18.], dtype=float32)>

In [15]:
print(t+10)
print(t*10)
print(t+t)
print(tf.square(t))

tf.Tensor(
[[22. 24. 18.]
 [32. 34. 28.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[120. 140.  80.]
 [220. 240. 180.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[24. 28. 16.]
 [44. 48. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[144. 196.  64.]
 [484. 576. 324.]], shape=(2, 3), dtype=float32)


In [22]:
t1=tf.Variable([[12.0, 14.0,8.0],[22.0, 24.0, 18.0]])
t1[1,0].assign(100)
t1


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 12.,  14.,   8.],
       [100.,  24.,  18.]], dtype=float32)>